#!/usr/bin/env bash

# import devos library.
curl -s https://raw.githubusercontent.com/vandenberghinc/devos/master/lib/import | bash 
if [[ "$OSTYPE" == "darwin"* ]] ; then source /usr/local/lib/devos/lib/import --silent ; else . /usr/local/lib/devos/lib/import --silent ; fi

# the alias.
alias="inc-package-manager"

# the source name.
source_name=$alias

# the pypi package name (may differ from alias).
pypi_name="inc_package_manager"

# boolean indicating whether the package is an pypi package.
pypi_package="true"

# boolean indicating whether to create a syst3m alias.
create_alias="true"

# pip requirements file (subpath) (leave "" to ignore).
pip_requirements="/requirements/requirements.pip"

# apt requirements file (subpath) (leave "" to ignore).
apt_requirements="/requirements/requirements.apt"

# brew requirements file (subpath) (leave "" to ignore).
brew_requirements="/requirements/requirements.brew"

# install the source code to a lib path (leave "" to ignore).
lib="/usr/local/lib/$alias/" 

# create an database directory (leave "" to ignore).
database="/etc/$alias/" 

# defaults.
source=$(source-path $(requirements-path $0))

# execute packge installer.
install-package \
    --alias $alias \
    --source $source \
    --source-name $source_name \
    --pypi-name $pypi_name \
    --pypi-package $pypi_package \
    --create-alias $create_alias \
    --pip-requirements $pip_requirements \
    --apt-requirements $apt_requirements \
    --brew-requirements $brew_requirements \
    --lib $lib \
    --database $database \
    $@ \

