#!/usr/bin/env bash

# the alias.
alias="inc-package-manager"

# the source name.
source_name=$alias

# the pypi package name (may differ from alias).
pypi_name="inc_package_manager"

# boolean indicating whether the package is an pypi package.
pypi_package="true"

# boolean indicating whether to create a syst3m alias.
create_alias="true"

# pip requirements file (subpath) (leave "" to ignore).
pip_requirements="/requirements/requirements.pip"

# apt requirements file (subpath) (leave "" to ignore).
apt_requirements="/requirements/requirements.apt"

# brew requirements file (subpath) (leave "" to ignore).
brew_requirements="/requirements/requirements.brew"

# install the source code to a lib path (leave "" to ignore).
lib="/usr/local/lib/$source_name/" 

# create an database directory (leave "" to ignore).
database="/etc/$source_name/" 

# import devos library.
curl https://raw.githubusercontent.com/vandenberghinc/devos/master/lib/import | bash 

# execute packge installer.
install-package \
    --alias $alias \
    --source-name $source_name \
    --pypi-name $pypi_name \
    --pypi-package $pypi_package \
    --create_alias $create_alias \
    --pip_requirements $pip_requirements \
    --apt_requirements $apt_requirements \
    --brew_requirements $brew_requirements \
    --lib $lib \
    --database $database \
    $@
